#version 460

layout(local_size_x = 1) in;

layout(std430, binding = 5) buffer particleNumPerBinSSBO {
    uint particleNumPerBin[];
};

layout(std430, binding = 7) buffer prefixForBinReorderSSBO {
    uint prefixForBinReorder[];
};

uniform uint binCount;
uniform uint totalParticles;

void main() {
    uint sum = 0;
    for (uint i = 0; i < binCount; ++i) {
        prefixForBinReorder[i] = sum;
        sum += particleNumPerBin[i];
    }
    prefixForBinReorder[binCount] = totalParticles;
}