#version 460

layout(local_size_x = 256) in;

layout(std430, binding = 5) buffer ForcesSSBO {
    vec4 forces[];
};

layout(std430, binding = 15) buffer prefixIndex {
    uint indexCount[];
};

uniform uint particleNum;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= particleNum) return;

    // positions[idx].w -= deltaTime;
    forces[idx] = vec4(0.0, 0.0, 0.0, 0.0);
    indexCount[idx] = 0;
}
